Ui login closes #30
DannyFeliz/Dashi pull request #48
Opened 2017-10-23 23:00 UTC by dawin09

2017-10-23 23:05 UTC, DannyFeliz requested changes
Please fix this

2017-10-23 23:05 UTC, DannyFeliz commented on public/js/scripts.js
> +    console.log("ready");
Remove this `console.log`

2017-10-23 23:05 UTC, DannyFeliz commented on public/js/scripts.js
> +        console.log("hola");
Same here

2017-10-23 23:05 UTC, DannyFeliz commented on resources/views/layouts/app.blade.php
> +                    </div>
Remove this zombie code

2017-10-23 23:05 UTC, DannyFeliz commented on resources/views/welcome.blade.php
> +        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
Why we have multiples jquery?

2017-10-23 23:05 UTC, DannyFeliz commented on public/js/jquery-1.11.1.min.js
> +/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
We already have jQuery 3, so remove this.

2017-10-23 23:20 UTC, DannyFeliz requested changes

2017-10-23 23:20 UTC, DannyFeliz commented on public/js/scripts.js
> +    if(WINDOWS_WIDTH > 768) {
What is 768?

2017-10-24 19:19 UTC, dawin09 commented
done, review the pr again

2017-10-24 19:31 UTC, DannyFeliz approved these changes

2017-10-24 19:32 UTC, merged