Add template to readme
DannyFeliz/Dashi pull request #60
Opened 2017-10-24 20:31 UTC by lepau

Remove setup steps from readme and add usage, contributing and license section to the readme.

2017-10-24 20:34 UTC, DannyFeliz requested changes

2017-10-24 20:34 UTC, DannyFeliz commented on README.md
> +1. Generate a Slack Incoming WebHook and copy the URL.
I think that the step 1 should be a link like:
Generate a [Slack Incoming WebHooks](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks)

2017-10-24 20:37 UTC, lepau commented
@DannyFeliz done.

2017-10-24 20:37 UTC, merged

2017-10-24 20:38 UTC, leninpaulino reviewed
Of course, I forget it.

2017-10-25 18:25 UTC, gabbanaesteban commented
resolve #62